### PR TITLE
Fix dotted secrets

### LINKED ISSUE #1005: [MI-4.1.0] Allowed characters for secret aliases in the [secrets] section of deployment.toml
### Description

Have a requirement to using "." characters in secret alias when using the cipher tool. After running the cipher tool and restarting the MI server they are getting the following error in the carbon logs.

```
ERROR {org.apache.synapse.transport.nhttp.config.ClientConnFactoryBuilder} - HTTPS Error opening Key store : repository/resources/security/raet-d-client-truststore.jks java.io.IOException: Keystore was tampered with, or password was incorrect
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.apache.synapse.transport.nhttp.config.ClientConnFactoryBuilder.createSSLContext(ClientConnFactoryBuilder.java:372)
        at org.apache.synapse.transport.nhttp.config.ClientConnFactoryBuilder.parseSSL(ClientConnFactoryBuilder.java:116)
        at org.apache.synapse.transport.passthru.PassThroughHttpSSLSender.initConnFactoryBuilder(PassThroughHttpSSLSender.java:45)
        at org.apache.synapse.transport.passthru.PassThroughHttpSender.init(PassThroughHttpSender.java:168)
        at org.apache.synapse.transport.passthru.PassThroughHttpSSLSender.init(PassThroughHttpSSLSender.java:33)
        at org.apache.axis2.context.ConfigurationContextFactory.initTransportSenders(ConfigurationContextFactory.java:300)
        at org.apache.axis2.context.ConfigurationContextFactory.init(ConfigurationContextFactory.java:231)
        at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:93)
        at org.wso2.micro.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:66)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initializeCarbon(CoreServerInitializer.java:209)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initMIServer(CoreServerInitializer.java:125)
        at org.wso2.micro.integrator.core.internal.Activator.start(Activator.java:92)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
        ... 34 more

[2022-11-15 10:44:34,721]  INFO {org.apache.axis2.context.ConfigurationContextFactory} - A transport-OUT initialization error: https
[2022-11-15 10:44:34,783] ERROR {org.apache.synapse.transport.nhttp.config.ServerConnFactoryBuilder} - HTTPS Error opening Key store : repository/resources/security/raet-d-client-truststore.jks java.io.IOException: Keystore was tampered with, or password was incorrect
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:792)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at org.apache.synapse.transport.nhttp.config.ServerConnFactoryBuilder.createSSLContext(ServerConnFactoryBuilder.java:201)
        at org.apache.synapse.transport.nhttp.config.ServerConnFactoryBuilder.createSSLContext(ServerConnFactoryBuilder.java:107)
        at org.apache.synapse.transport.nhttp.config.ServerConnFactoryBuilder.parseSSL(ServerConnFactoryBuilder.java:312)
        at org.apache.synapse.transport.passthru.PassThroughHttpSSLListener.initConnFactoryBuilder(PassThroughHttpSSLListener.java:20)
        at org.apache.synapse.transport.passthru.PassThroughHttpListener.init(PassThroughHttpListener.java:184)
        at org.apache.axis2.engine.ListenerManager.init(ListenerManager.java:84)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initializeCarbon(CoreServerInitializer.java:220)
        at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initMIServer(CoreServerInitializer.java:125)
        at org.wso2.micro.integrator.core.internal.Activator.start(Activator.java:92)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
        at org.eclipse.osgi.container.Module.doStart(Module.java:598)
        at org.eclipse.osgi.container.Module.start(Module.java:462)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
        at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
Caused by: java.security.UnrecoverableKeyException: Password verification failed
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:790)
        ... 31 more
```

### Steps to Reproduce

Take an MI-4.1.0 pack and update to the U2 level 19.
Open the toml configuration and use the following alias value under [secrets] section in the deployment.toml file.
```
[secrets]
truststore.password = "[wso2carbon]"
```

Replace the password of the trusstore with the alias value defined in the secret section.

```
[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "$secret{truststore.password}"
alias = "symmetric.key.value"
algorithm = "AES"
```
Encrypt the password using the cipher tool.

`./ciphertool.sh -Dconfigure
`
Restart the MI server after executing the cipher tool.

### Affected Component

MI

### Version

4.1.0

### Suggested Labels

MI-4.1.0

### PR DESCRIPTION
**Pull request by Tharsanan1**

### CODE REVIEW

File: src/main/java/org/wso2/config/mapper/TomlParser.java [hunk 1]
```diff
@@ -128,14 +128,26 @@ private static Map<String, String> processSecrets(TomlParseResult result) {
...
         }
         return context;
     }
 
+    /**
+     * Extract key surrounded by double quotes.
+     * @param key
+     * @return key value without surrounding double quotes
+     */
+    static String filterDottedContent(String key) {
```
Comment (senthuran16) [inline src/main/java/org/wso2/config/mapper/TomlParser.java]: Shall we rename this method as `extractQuotedContent`, since that would be a more meaningful name for its functionality?

File: src/main/java/org/wso2/config/mapper/TomlParser.java [hunk 2]
```diff
@@ -128,14 +128,26 @@ private static Map<String, String> processSecrets(TomlParseResult result) {
...
+        if (key.startsWith("\"") && key.endsWith("\"")) {
```
Comment (senthuran16) [inline src/main/java/org/wso2/config/mapper/TomlParser.java]: Shall we define a constant for `\"` and reuse?
Let's do a null check `key != null` as well

**Review by senthuran16 — CHANGES_REQUESTED** [review]

**Review by madushadhanushka — DISMISSED** [review]

File: src/main/java/org/wso2/config/mapper/TomlParser.java (hunk 1 above)
Comment (Tharsanan1) [reply src/main/java/org/wso2/config/mapper/TomlParser.java]: Updated the method name.

File: src/main/java/org/wso2/config/mapper/TomlParser.java (hunk 2 above)
Comment (Tharsanan1) [reply src/main/java/org/wso2/config/mapper/TomlParser.java]: Yeah, Updated.

**Review by senthuran16 — APPROVED** [review]
